name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master
      - testing

jobs:
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'latest'

    - name: Install Bundler
      run: |
        gem install bundler

    - name: Install Dependencies
      run: |
        bundle install

    - name: Build Jekyll Site
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_dir: master

  build-testing:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/testing'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'latest'

    - name: Install Bundler
      run: |
        gem install bundler

    - name: Install Dependencies
      run: |
        bundle install

    - name: Build Jekyll Site
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_dir: testing
