name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master
      - testing

jobs:
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Jekyll Docker image
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
        jekyll/builder:latest \
        jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_dir: master

  build-testing:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/testing'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Jekyll Docker image
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
        jekyll/builder:latest \
        jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_dir: testing
