name: GitHub Pages

on:
  push:
    branches:
      - master
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build master
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --destination ./public/master

      - name: Build testing
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config.testing.yml --destination ./public/testing

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          cname: yourdomain.com
          keep_history: true
          deploy_to: |
            master: /
            testing: /testing
